  <DIV class=nav-links>
<UL class="nice-menu nice-menu-down" id=nice-menu-0>
  <LI class="menuparent menu-path-front" id=menu-161><A class=active
  title="Home Page" href="index.jsp">Home</A>
  <LI  class="menuparent menu-path-node-134" id="menu-271"><A class=active>About</a>
 
  <UL>
    <LI class=menu-path-node-134 id=menu-264><a href="/DNB/dnb_aboutsite.jsp">About the Site</a></LI>
        <LI class=menu-path-node-136 id=menu-568><a href="/DNB/dnb_aboutdata.jsp">About the Data</a></LI>
        <LI class=menu-path-node-135 id=menu-416><a href="/DNB/api_doc/dnb_glossary.jsp">Glossary</a></LI>
  </UL></LI>
        <LI class="menuparent menu-path-node-134" id=menu-271><A class=active>Company</a>
  <ul>
        <li class=menu-path-node-134 id=menu-264><a href="/DNB/ora_grsCompany.jsp">Company Search</a></li>
        <li class=menu-path-node-136 id=menu-568><a href="/DNB/ora_grsCorporateStructure.jsp">Corporate Structure</a></li>
        <li class=menu-path-node-135 id=menu-416><a href="/DNB/ora_grsBusinessSize.jsp">Size of Corporation</a></li>
        <li class=menu-path-node-133 id=menu-414><a href="/DNB/ora_grsSICSearch.jsp">Search by Industry Sector</a></li>
        <!--
        <li class=menu-path-node-90 id=menu-268><a href="/DNB/ora_prox_search.jsp">Proximity Search</a></li>
        -->
  </ul></LI>
        <LI class="menuparent menu-path-node-134" id=menu-271><A class=active>Executive</a>
  <ul>
        <li class=menu-path-node-134 id=menu-264><a href="/DNB/ora_executive_search.jsp">Executive Search</a></li>
  </ul></LI>
        <LI class="menuparent menu-path-node-134" id=menu-271><A class=active>i2 Import</a>
  <ul>
        <li class=menu-path-node-134 id=menu-264><a href="/DNB/i2_import_spec.jsp">i2 Import Specification</a></li>
  </ul></LI>

    <LI  class="menuparent menu-path-node-134" id=menu-264><A title="API"
  href="api_doc.jsp">API</A>
  <ul>
  <li  class=menu-path-node-74 id=menu-264><a href="/DNB/api_doc.jsp">API</a></li>
    <LI class=menu-path-node-135 id=menu-416><a href="/DNB/api_doc/dnb_datadictionary.jsp">Data Dictionary</a></LI>

  </ul></LI>
        <LI class="menuparent menu-path-node-134" id=menu-271><A class=active>Help</a>
  <ul>
        <li class=menu-path-node-134 id=menu-264><a href="/DNB/help/faq.jsp">FAQ</a></li>
        <li class=menu-path-node-135 id=menu-414><a href="/DNB/help/quickstart.jsp">Quick Start</a></li>
  </ul></LI>
</UL>
	</div>